#
# Blog Settings
#
author: Phil Haack
description: You've been Haacked and you like it is a blog about Technology, Software, Management, and Open Source. It's full of good stuff.
url: https://haacked.com
title: You've Been Haacked
subtitle: ...and you like it
gravatar_url: https://2.gravatar.com/avatar/cdf546b601bf29a7eb4ca777544d11cd
subscribe_rss: http://feeds.haacked.com/haacked
lang: en

# Github repositories
github_user: haacked
github_repo_url: https://github.com/Haacked/haacked.com/

# Twitter
twitter_user: haacked
twitter:
  username: haacked
twitter_tweet_button: true

# Disqus Comments
disqus_short_name: haacked
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-177588-1

social:
  name: Phil Haack
  links:
    - https://twitter.com/haacked
    - https://www.facebook.com/haacked
    - https://www.linkedin.com/in/haacked
    - https://github.com/haacked

kramdown:
  hard_wrap: false

#
# Jekyll Settings
#
permalink: /archive/:year/:month/:day/:title/
paginate: 20
paginate_path: "page/:num"
category_dir: categories

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

feed:
  path: atom.xml

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed
